server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exampledb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    date-format: yyyy-MM-dd